USE [master]
GO

/****** Object:  Database [Crud_App_Esp]    Script Date: 16/11/2021 18:57:11 ******/
CREATE DATABASE [Crud_App_Esp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Crud_App_Esp', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Crud_App_Esp.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Crud_App_Esp_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Crud_App_Esp_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Crud_App_Esp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Crud_App_Esp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET ARITHABORT OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Crud_App_Esp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Crud_App_Esp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Crud_App_Esp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Crud_App_Esp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Crud_App_Esp] SET  MULTI_USER 
GO

ALTER DATABASE [Crud_App_Esp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Crud_App_Esp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Crud_App_Esp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Crud_App_Esp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Crud_App_Esp] SET  READ_WRITE 
GO


